apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: apache
  name: apache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http-search-service
  selector:
    run: apache
  type: LoadBalancer
status:
  loadBalancer: {}