version: '3.2'
services:
  # web-shop-db-image:
  #     image: mavogel/hska-vis-web-shop-db-image
  #     volumes:
  #       - "./.data/db:/var/lib/mysql"
  #       - "./.docker/mysql/init/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql"
  #     environment:
  #       MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
  #       MYSQL_DATABASE: webshop
  #       MYSQL_USER: webshopuser
  #       MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
  #     ports:
  #       - "3306:3306"
  #     networks:
  #       local-dev-net:
  #         aliases:
  #           - web-shop-db-image
  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/dockerfile
    image: web-shop-db-image
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    # networks:
    #     local-dev-net:
    #         aliases:
    #             - web-shop-db-image
#  legacywebshop:
#    image: mavogel/hska-vis-legacywebshop
#    ports:
#      - "8888:8080"
#    networks:
#      local-dev-net:
#        aliases:
#          - legacywebshop

  product-service:
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    image: product-service
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=web-shop-db-image
    depends_on:
      - "web-shop-db-image"
    # networks:
    #   local-dev-net:
    #     aliases:
    #       - product-service

  search-service:
    build:
      context: ./search-service
      dockerfile: ./Dockerfile
    image: search-service
    ports:
      - "8082:8082"
    # networks:
    #   local-dev-net:
    #     aliases:
    #       - search-service

  apache:
    build:
      context: ./apache
      dockerfile: ./Dockerfile
    image: apache
    ports:
      - "80:80"
    # networks:
    #   local-dev-net:
    #     aliases:
    #       - apache

# networks:
#   local-dev-net:
#     driver: bridge
