version: '3.2'
services:

  legacywebshop:
    build:
      context: ./hska-vis-legacy
      dockerfile: ./docker/Dockerfile
    image: legacywebshop
    ports:
      - "8080:8080"
    # networks:
    #   local_dev_net:
    #     aliases:
    #       - legacywebshop

  web-shop-db-image:
    build:
      context: ./hska-vis-legacy
      dockerfile: ./docker/DockerfileMySQL
    image: web-shop-db-image
    volumes:
      - "./hska-vis-legacy/.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    # networks:
    #   local_dev_net:
    #     aliases:
    #       - web-shop-db-image

  product-service:
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    image: product-service
    ports:
      - "8081:8081"
    depends_on:
      - "web-shop-db-image"
    # networks:
    #   local_dev_net:
    #     aliases:
    #       - product-service

  category-service:
    build:
      context: ./category-service
      dockerfile: ./Dockerfile
    image: category-service
    ports:
      - "8085:8085"
    depends_on:
      - "web-shop-db-image"
    # networks:
    #   local_dev_net:
    #     aliases:
    #       - category-service

  apache:
    build:
      context: ./apache
      dockerfile: ./Dockerfile
    image: apache
    ports:
      - "80:80"
    # networks:
    #   local_dev_net:
    #     aliases:
    #       - apache

# networks:
#   local_dev_net:
#     driver: bridge
