###

GET http://localhost:8081/api/product/999

###

GET http://localhost:8081/api/product/3

###

GET http://localhost:8081/api/product/all

###

POST http://localhost:8081/api/product/add
Content-Type: application/json

{
  "name": "Zitrone",
  "price": 1.0,
  "categoryId": 1,
  "details": "gelb"
}

###

POST http://localhost:8081/api/product/add
Content-Type: application/json

{
  "name": "Spinat",
  "price": 5.0,
  "categoryId": 3,
  "details": "gruen"
}

###

POST http://localhost:8085/api/category/add
Content-Type: application/json

{
  "name": "Beilagen"
}

###

POST http://localhost:8085/api/category/add
Content-Type: application/json

{
  "name": "Gemuese"
}

###


GET http://localhost:8085/api/category/all
Content-Type: application/json


###


GET http://localhost:8085/api/category/1
Content-Type: application/json


###

DELETE http://localhost:8081/api/product/4

###

DELETE http://localhost:8081/api/product/category/78


###

POST http://127.0.0.1:53213/product-service/api/product/add
Content-Type: application/json

{
  "name": "Kiwi",
  "price": 2.0,
  "categoryId": 1,
  "details": "gruen"
}

###

GET http://localhost:8081/api/product/search?priceMin=2&priceMax=9

###


GET http://localhost:8082/search?term=spinat&priceMin=2

###