###

GET http://localhost:8081/product-service/api/product/999

###

GET http://localhost:8081/product-service/api/product/2

###

GET http://product-service:8081/product-service/api/product/all

###

POST http://product-service:8081/product-service/api/product/add
Content-Type: application/json

{
  "name": "Zitrone",
  "price": 1.0,
  "categoryId": 1,
  "details": "gelb"
}

###

DELETE http://localhost:8081/product-service/api/product/3

###

POST http://localhost:8081/product-service/api/product/add
Content-Type: application/json

{
  "name": "Kiwi",
  "price": 2.0,
  "categoryId": 1,
  "details": "gruen"
}

###

GET http://localhost:8082/search?term=kiwi

###