apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    run: product-service
  type: LoadBalancer
status:
  loadBalancer: {}
