apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: search-service
  name: search-service
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    run: search-service
  type: LoadBalancer
status:
  loadBalancer: {}
