apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: search-service
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: search-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/local-dev-net: "true"
        io.kompose.service: search-service
    spec:
      containers:
        - image: search-service
          imagePullPolicy: Never
          name: search-service
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
