apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: web-shop-db-image
  name: web-shop-db-image
spec:
  ports:
    - name: "db-port"
      port: 3306
      targetPort: 3306
  selector:
    run: web-shop-db-image
status:
  loadBalancer: {}
