version: '3.2'
services:

  web-shop-db-image:
    image: mavogel/hska-vis-web-shop-db-image
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.databases/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
      local_dev_net:
        aliases:
          - web-shop-db-image

  product-service:
    image: joma1021/product-service-docker
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=web-shop-db-image
    depends_on:
      - "web-shop-db-image"
    networks:
      local_dev_net:
        aliases:
          - product-service

networks:
  local_dev_net:
    driver: bridge
